config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :chats, only: [ :edit, :create, :update, :destroy, :show ] do
    collection do
      post :create_message
    end
    member do
      resources :messages, only: [ :create ]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  default_scope { order('created_at ASC') }
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy

  validates :title, presence: true

  accepts_nested_attributes_for :messages
end

app/models/embedding.rb
class Embedding < ApplicationRecord
  has_neighbors :embedding
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat

  enum role: { user: "user", system: "system", assistant: "assistant" }


  validates :content, presence: true
  validates :role, presence: true

  after_create :create_assistant_message, if: -> { self.user? }
  after_update :udpate_chat_title, if: -> { self.chat.messages.count == 4 }

  private

  def create_assistant_message
    message = self.chat.messages.create(content: "...", role: "assistant")
    OpenAi::Chat::CreateMessageJob.perform_async({message_id: message.id}.to_json)
  end

  def udpate_chat_title
    OpenAi::Chat::UpdateChatTitleJob.perform_async({ chat_id: self.chat_id }.to_json)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  def show
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(title: "New chat")

    respond_to do |format|
      if @chat.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_message
    @chat = Chat.new(chat_params.merge(title: "New chat"))

    respond_to do |format|
      if @chat.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Chat was successfully destroyed." }
      format.turbo_stream
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:title, messages_attributes: [ :content ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # POST /:id/messages or /messages.json
  def create
    @chat = Chat.find(params[:id])
    @message = @chat.messages.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.turbo_stream
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:chat_id, :content, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/_chat.html.erb
<%= turbo_frame_tag chat do %>
  <div class="p-1 rounded-md flex items-center justify-between hover:bg-gray-800">
    <%= button_to chat.title, chat_url(chat, host: "localhost", port: "3000"), method: :get, data: { turbo_stream: true }, class: "text-left text-nowrap w-24 md:w-42 text-ellipsis overflow-hidden text-gray-200 hover:text-white hover:underline" %>
    <div class="flex items-center space-x-2">
      <%= button_to edit_chat_url(chat, host: "localhost", port: "3000"), method: :get, class: "text-gray-400 hover:text-white flex items-center" do %>
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-md"><path fill-rule="evenodd" clip-rule="evenodd" d="M13.2929 4.29291C15.0641 2.52167 17.9359 2.52167 19.7071 4.2929C21.4783 6.06414 21.4783 8.93588 19.7071 10.7071L18.7073 11.7069L11.1603 19.2539C10.7182 19.696 10.1489 19.989 9.53219 20.0918L4.1644 20.9864C3.84584 21.0395 3.52125 20.9355 3.29289 20.7071C3.06453 20.4788 2.96051 20.1542 3.0136 19.8356L3.90824 14.4678C4.01103 13.8511 4.30396 13.2818 4.7461 12.8397L13.2929 4.29291ZM13 7.41422L6.16031 14.2539C6.01293 14.4013 5.91529 14.591 5.88102 14.7966L5.21655 18.7835L9.20339 18.119C9.40898 18.0847 9.59872 17.9871 9.7461 17.8397L16.5858 11L13 7.41422ZM18 9.5858L14.4142 6.00001L14.7071 5.70712C15.6973 4.71693 17.3027 4.71693 18.2929 5.70712C19.2831 6.69731 19.2831 8.30272 18.2929 9.29291L18 9.5858Z" fill="currentColor"></path></svg>
      <% end %>
      <%= button_to chat_url(chat, host: "localhost", port: "3000"), method: :delete, class: "hover:text-red-600 text-red-800 flex items-center" do %>
        <svg width="19" height="19" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class=""><path fill-rule="evenodd" clip-rule="evenodd" d="M10.5555 4C10.099 4 9.70052 4.30906 9.58693 4.75114L9.29382 5.8919H14.715L14.4219 4.75114C14.3083 4.30906 13.9098 4 13.4533 4H10.5555ZM16.7799 5.8919L16.3589 4.25342C16.0182 2.92719 14.8226 2 13.4533 2H10.5555C9.18616 2 7.99062 2.92719 7.64985 4.25342L7.22886 5.8919H4C3.44772 5.8919 3 6.33961 3 6.8919C3 7.44418 3.44772 7.8919 4 7.8919H4.10069L5.31544 19.3172C5.47763 20.8427 6.76455 22 8.29863 22H15.7014C17.2354 22 18.5224 20.8427 18.6846 19.3172L19.8993 7.8919H20C20.5523 7.8919 21 7.44418 21 6.8919C21 6.33961 20.5523 5.8919 20 5.8919H16.7799ZM17.888 7.8919H6.11196L7.30423 19.1057C7.3583 19.6142 7.78727 20 8.29863 20H15.7014C16.2127 20 16.6417 19.6142 16.6958 19.1057L17.888 7.8919ZM10 10C10.5523 10 11 10.4477 11 11V16C11 16.5523 10.5523 17 10 17C9.44772 17 9 16.5523 9 16V11C9 10.4477 9.44772 10 10 10ZM14 10C14.5523 10 15 10.4477 15 11V16C15 16.5523 14.5523 17 14 17C13.4477 17 13 16.5523 13 16V11C13 10.4477 13.4477 10 14 10Z" fill="currentColor"></path></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <%= form.text_field :title, class: "focus:ring-0 focus:text-gray-200 bg-transparent text-gray-200 block rounded-md border border-gray-200 outline-none py-1 w-full", onfocusout: 'this.form.requestSubmit()' %>
<% end %>

app/views/chats/_job_chat_update.turbo_stream.erb
<%= turbo_stream.update :title do %>
  <%= render "home/title", title: chat.title %>
<% end %>
<%= turbo_stream.replace_all chat %>

app/views/chats/create.turbo_stream.erb
<%= turbo_stream.append_all "#chats", @chat %>
<%= turbo_stream.update :title do %>
  <%= render "home/title", title: @chat.title %>
<% end %>
<%= turbo_stream.update :messages do %>
  <%= render "home/messages", chat: @chat %>
<% end %>

app/views/chats/create_message.turbo_stream.erb
<%= turbo_stream.update :messages do %>
  <%= render "home/messages", chat: @chat %>
<% end %>
<%= turbo_stream.update :title do %>
  <%= render "home/title", title: @chat.title %>
<% end %>
<%= turbo_stream.append_all "#chats", @chat %>

app/views/chats/destroy.turbo_stream.erb
<%= turbo_stream.remove_all @chat %>
<%= turbo_stream.update :title do %>
  <%= render "home/title", title: nil %>
<% end %>
<%= turbo_stream.update :messages do %>
  <%= render "home/messages", chat: nil %>
<% end %>

app/views/chats/edit.html.erb
<%# @NOTE: This is left as an example. Can be refactored using turbo streams.  %>
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing chat</h1>
  <%= turbo_frame_tag @chat do %>
    <%= render "form", chat: @chat %>
  <% end %>
  <%= link_to "Show this chat", @chat, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to chats", chats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/chats/show.turbo_stream.erb
<%= turbo_stream.update :title do %>
  <%= render "home/title", title: @chat.title %>
<% end %>
<%= turbo_stream.update :messages do %>
  <%= render "home/messages", chat: @chat %>
<% end %>

app/views/chats/update.turbo_stream.erb
<%= turbo_stream.update_all @chat %>
<%= turbo_stream.update :title do %>
  <%= render "home/title", title: @chat.title %>
<% end %>
<%= turbo_stream.update :messages do %>
  <%= render "home/messages", chat: @chat %>
<% end %>

app/views/home/_messages.html.erb
<%-
  if chat.nil?
    url = create_message_chats_path
    model = Chat.new
    model.messages.new
  else
    url = messages_path(chat)
    model = Message.new
  end
-%>
<% if chat.present? %>
  <%= turbo_stream_from dom_id(chat) %>
<% end %>
<div class="px-4 sm:px-6 lg:px-8 text-gray-800">
  <div class="flex flex-col items-center space-y-2 mb-2">
    <% if chat.nil? %>
      <div class="rounded-lg p-4 mb-32 border-4 border-dashed flex justify-center items-center">
        <h1 class="text-center md:text-2xl text-xl text-gray-500">Send a message to start a new conversation ⚡️</h1>
      </div>
    <% else %>
      <%= render chat.messages %>
    <% end %>
  </div>
  <%= form_with model: model, url: url, method: :post, class: "flex justify-center items-center" do |f| %>
    <% if chat.nil? %>
      <%= f.fields_for :messages do |messages_form| %>
        <%= messages_form.text_field :content, placeholder: "Message ChatGPT... ", autocomplete: "off", class: "mr-3 focus:ring-0 focus:border-gray-400 rounded-xl border border-gray-400 py-2 px-2 w-full" %>
      <% end %>
    <% else %>
      <%= f.text_field :content, placeholder: "Message ChatGPT... ", autocomplete: "off", class: "mr-3 focus:ring-0 focus:border-gray-400 rounded-xl border border-gray-400 py-2 px-2 w-full" %>
    <% end %>
    <%= f.button "", class: "rounded-xl border border-gray-400 py-2 px-2" do %>
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" class="text-gray-200 dark:text-black"><path d="M7 11L12 6L17 11M12 18V7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg>
    <% end %>
  <% end %>
</div>

app/views/home/_title.html.erb
<%= turbo_frame_tag :title do %>
  <h1 class="text-2xl font-bold text-gray-700"><%= title %></h1>
<% end %>

app/views/home/index.html.erb
<%= content_for :chats do %>
  <nav class="flex flex-1 flex-col" id="chats">
    <%= render Chat.all %>
  </nav>
<% end %>
<%= content_for :title do %>
  <%= render "title", title: nil %>
<% end %>
<%= content_for :messages do %>
  <%= turbo_frame_tag :messages do %>
    <%= render "messages", chat: nil %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title>TurboChatGptRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="h-full">
    <div data-controller="slide-over" class="h-full">
      <div class="relative z-50 lg:hidden hidden" role="dialog" aria-modal="true" data-slide-over-target="container">
        <div
      class="fixed inset-0 bg-gray-900/80"
      data-slide-over-target="backdrop"
      data-transition-enter="transition-opacity ease-linear duration-300"
      data-transition-enter-start="opacity-0"
      data-transition-enter-end="opacity-100"
      data-transition-leave="transition-opacity ease-linear duration-300"
      data-transition-leave-start="opacity-100"
      data-transition-leave-end="opacity-0"></div>
        <div class="fixed inset-0 flex">
          <div
        class="relative mr-16 flex w-full max-w-xs flex-1"
        data-slide-over-target="panel"
        data-transition-enter="transition ease-in-out duration-300 transform"
        data-transition-enter-start="-translate-x-full"
        data-transition-enter-end="translate-x-0"
        data-transition-leave="transition ease-in-out duration-300 transform"
        data-transition-leave-start="translate-x-0"
        data-transition-leave-end="-translate-x-full">
            <div
          class="absolute left-full top-0 flex w-16 justify-center pt-5"
          data-slide-over-target="closeButton"
          data-transition-enter="ease-in-out duration-300"
          data-transition-enter-start="opacity-0"
          data-transition-enter-end="opacity-100"
          data-transition-leave="ease-in-out duration-300"
          data-transition-leave-start="opacity-100"
          data-transition-leave-end="opacity-0">
              <button type="button" class="-m-2.5 p-2.5" data-action="slide-over#hide">
                <span class="sr-only">Close sidebar</span>
                <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <%= render "layouts/sidebar" %>
          </div>
        </div>
      </div>
      <div class="hidden lg:fixed lg:inset-y-0 lg:z-50 lg:flex lg:w-72 lg:flex-col">
        <%= render "layouts/sidebar" %>
      </div>
      <div class="lg:pl-72 h-full flex flex-col justify-between">
        <div class="sticky top-0 z-40 flex h-16 shrink-0 items-center gap-x-4 border-b border-gray-200 bg-white px-4 shadow-sm sm:gap-x-6 sm:px-6 lg:px-8">
          <button type="button" class="-m-2.5 p-2.5 text-gray-700 lg:hidden" data-action="slide-over#show">
            <span class="sr-only">Open sidebar</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </button>
          <%= yield :title %>
        </div>
        <main class="py-10">
          <%= yield :messages %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/messages/_job_message_update.turbo_stream.erb
<%= turbo_stream.replace message %>

app/views/messages/_message.html.erb
<% if message.user? %>
  <div id="<%= dom_id message %>" class="border border-gray-400 rounded-t-lg rounded-l-lg p-2 self-end ml-3">
    <%= message.content %>
  </div>
<% else %>
  <div id="<%= dom_id message %>" class="border border-gray-400 rounded-t-lg rounded-r-lg p-2 self-start mr-3">
    <%= message.content %>
  </div>
<% end %>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.update :messages do %>
  <%= render "home/messages", chat: @chat %>
<% end %>